language: go

go:
  - 1.9.x

# Only clone the most recent commit.  
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in the repo
install: true

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)